WVSTREAMS_VERSION = 4.6.1
WVSTREAMS_SOURCE = wvstreams-$(WVSTREAMS_VERSION).tar.gz
WVSTREAMS_SITE = http://wvstreams.googlecode.com/files
WVSTREAMS_INSTALL_STAGING = YES
WVSTREAMS_INSTALL_TARGET = YES
WVSTREAMS_CONF_OPT = --without-dbus
WVSTREAMS_DEPENDENCIES = openssl
WVSTREAMS_MAKE=$(MAKE1)

$(eval $(call AUTOTARGETS))

