#!/bin/sh

source "/etc/profile.d/icd.sh"

start()
{
  echo "Starting icd: "

  # nodes for fotodetectors and lcd display
  if [ ! -c /dev/itd0 ]; then
    mknod /dev/itd0 c 251 0
    mknod /dev/itd1 c 251 1
    mknod /dev/itd2 c 251 2
    mknod /dev/itd3 c 251 3
    mknod /dev/lcd0 c 250 0
    # workaround because driver output (mknod .. c) is unbuffered 
    # and can't work properly with poll() (mknod .. p works)
    mknod /tmp/itd0 p
    mknod /tmp/itd1 p
    mknod /tmp/itd2 p
    mknod /tmp/itd3 p
    cat /dev/itd0 >> /tmp/itd0 &
    cat /dev/itd1 >> /tmp/itd1 &
    cat /dev/itd2 >> /tmp/itd2 &
    cat /dev/itd3 >> /tmp/itd3 &
    echo "++mknod itdX"
  fi


  # databases
  icd-create-data 
  icd-create-live-db 
  echo "++databases"

  # daemon for all networks: eth, wifi, gsm
  icd-run-daemon --logfile="/tmp/log/net_daemon.log" -- icd-net 
  echo "++network"

  # daemon for lcd and buttons
  icd-run-daemon --nolog -- icd-fc-daemon

  # daemon for fotodetectors
  icd-run-daemon -- icd-counters-daemon

  # daemon for data transfer and sync db
  icd-run-daemon --nolog -- icd-cron 

  echo "++daemons"


  echo "Start icd DONE"
}	

case "$1" in
  start)
    start
    ;;
  *)
    echo $"Usage: $0 {start}"
    exit 1
esac

exit $?

