#!/bin/sh
#
# icd				Starts icd.
#
source "/etc/profile.d/icd.sh"

start()
{
  echo "Starting icd: "

  # nodes for fotodetectors and lcd display
  if [ ! -c /dev/itd0 ]; then
    mknod /dev/itd0 c 251 0
    mknod /dev/itd1 c 251 1
    mknod /dev/itd2 c 251 2
    mknod /dev/itd3 c 251 3
    mknod /dev/lcd0 c 250 0
    echo "++mknod itdX"
  fi


  # databases TODO:
  icd-create-data 
  icd-create-live-db 

  echo "++databases"

  icd-network start & #> /dev/null 2>&1 &

  echo "++network"

  icd-wifi-daemon &

  echo "++wifi"

  # daemon for lcd and buttons
  start-stop-daemon -S -p /tmp/icd-fc-daemon.pid -a icd-fc-daemon \
    -- --daemon --pidfile="/tmp/icd-fc-daemon.pid"

  # daemon for fotodetectors
  start-stop-daemon -S -p /tmp/icd-itd-daemon-itd0.pid -a icd-itd-daemon -- \
    --daemon --pidfile="/tmp/icd-itd-daemon-itd0.pid"

  #TODO:
  # daemon for data transfer
  icd-cron --daemon --pidfile="/tmp/icd-cron.pid"

  echo "++daemons"

  echo "Start icd DONE"
}	

case "$1" in
  start)
    start
    ;;
  *)
    echo $"Usage: $0 {start}"
    exit 1
esac

exit $?

