#!/bin/sh
#
# icd        Starts icd.
#
source "/etc/profile.d/icd.sh"

start()
{
  echo "Starting icd:"

  if [ ! -c /dev/itd0 ]; then
    mknod /dev/itd0 c 251 0
    mknod /dev/itd1 c 251 1
    mknod /dev/itd2 c 251 2
    mknod /dev/itd3 c 251 3
    mknod /dev/lcd0 c 250 0
  fi

  umask 000

  icd-create-config-db
  icd-create-flow-db
  icd-create-live-db
  icd-init-last-aggr-time

  chmod a+w "/tmp/live.db"

  icd-network start

  start-stop-daemon -S -p /tmp/icd-fc-daemon.pid -a icd-fc-daemon \
    -- --db="/tmp/live.db" --daemon --pidfile="/tmp/icd-fc-daemon.pid"

#  ls /dev/itd*

  start-stop-daemon -S -p /tmp/icd-itd-daemon-itd0.pid -a icd-itd-daemon -- \
    --db="/tmp/live.db" --device="itd0" --daemon \
    --pidfile="/tmp/icd-itd-daemon-itd0.pid"
}	

stop()
{
  echo -n "Stopping sshd: "
  icd-network start
}

restart() 
{
 stop
 start
}	

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

